### PR TITLE
binary transport

### PR DESCRIPTION
**Pull request by jankin-l**
Binary transmission support

### CODE REVIEW

**Comment by ibc** [comment]
Sending a binary payload cannot be  designed this way. protoo has notifications and requests and responses to requests. Binary payload cannot be a separate message type. Sorry, I cannot accept this PR.

**Comment by jankin-l** [comment]
ok~, it doesn't matter

But 
first,  I designed the binary transfer to not conflict with the previous features (requests, responses, notifications).
second，The protoo should not lose the transmission binary feature of websocket.
third，Fox example upload file: setup connection -> send data block -> close connection, like this, there is no need to keep a long connection to transmit binary data. 
fourth，I used protoo in my project and some service scenarios require sending binary data. If I use another websocket package，I have to maintain two ways of using websocket，so I modify protoo to support binary transfers.

**Comment by ibc** [comment]
I'm not against the binary feature. It's just that the way you have added binary into protoo is exactly the way is done in raw WebSocket. Now imagine you want to send a protoo request and have a binary body as response. We need a proper protoo response with proper id field and a binary data field into it. That's the way it must be done.

**Comment by jankin-l** [comment]
Maybe I didn't make myself clear.
You mean, the binary is payload for protoo in requests, responses, notifications. Binary doesn't make sense in this case. I agree !
I mean, the binary is in a stream, be used for files, images, videos, anything transfer, it does not participate in the request, It doesn't respond. It is independent of the request response pattern.
For example. I want upload a file to the server. Maybe I first send a request telling the server to create a file, then send a series of binary data, just like a stream. After the end, send another request to tell the server it's done.

**Comment by ibc** [comment]
That's not how a real protocol works. In a real protocol you send a notification with its corresponding notification name or type plus more metadata (such as `chunkId`) plus a binary body. Imagine you want to upload two files at the same time by sending separate chunks of both files at the same time. That's why we need a real protocol and not just a way to send binary chunks.

**Comment by jankin-l** [comment]
Yes, It cannot transfer two files at the same time. 
but this is just a json protocol，Message class { id, method, data }，the format is fixed, use JSON.stringify  then socket send. I try to put binary in `message.data`，this increases the size of the message. The data sent will be much larger than the file size.
The chunkId and binary body in Message，It's impossible，unless you make big changes to protoo. 
Maybe add a layer of binary protocol before the JSON protocol. Is this necessary？ I can transfer one file at the same time and I think that's fine, it better than nothing.

**Comment by ibc** [comment]
Binary payload support will be properly implemented in some weeks, but approach in current PR is not the way to go.

**Comment by jankin-l** [comment]
ok, thanks

**Pull request closed without merging**
